USE miliroutine_db;

insert into goods (id, name, description, thumbnail_img, price) values (1, 'Paradise Tansymustard', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'http://dummyimage.com/240x271.png/cc0000/ffffff', 4003);
insert into goods (id, name, description, thumbnail_img, price) values (2, 'Rosha Grass', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/233x183.png/cc0000/ffffff', 2240);
insert into goods (id, name, description, thumbnail_img, price) values (3, 'Littlepod False Flax', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'http://dummyimage.com/494x238.png/ff4444/ffffff', 3074);
insert into goods (id, name, description, thumbnail_img, price) values (4, 'Berlandier''s Trumpets', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/363x237.png/dddddd/000000', 1043);
insert into goods (id, name, description, thumbnail_img, price) values (5, 'Elephanthead Lousewort', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/257x260.png/ff4444/ffffff', 284);
insert into goods (id, name, description, thumbnail_img, price) values (6, 'American Alumroot', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/335x113.png/dddddd/000000', 4789);
insert into goods (id, name, description, thumbnail_img, price) values (7, 'Ragged Lichen', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/119x416.png/cc0000/ffffff', 2620);
insert into goods (id, name, description, thumbnail_img, price) values (8, 'Truncate Pottia Moss', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'http://dummyimage.com/490x230.png/dddddd/000000', 4515);
insert into goods (id, name, description, thumbnail_img, price) values (9, 'Bottlebrush Threeawn', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/211x424.png/cc0000/ffffff', 2100);
insert into goods (id, name, description, thumbnail_img, price) values (10, 'Autumn Zephyrlily', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/218x211.png/dddddd/000000', 3830);
